### ISSUE TITLE
Navigation problem

### ISSUE THREAD

**Issue by navinpatel89** [wingman007/fmi#125]
Dear Friends,

I have download your source code and setup. Also I have created virtual host. 
When I hit in URL. I was getting error like this 
Fatal error: Uncaught exception 'Zend\Navigation\Exception\BadMethodCallException' with message 'Bad method call: Unknown method Zend\Navigation\Navigation::setAddClassToListItem' in C:\xampp\htdocs\fmi\vendor\zendframework\zendframework\library\Zend\Navigation\AbstractContainer.php:354 Stack trace: #0 [internal function]: Zend\Navigation\AbstractContainer->__call('setAddClassToLi...', Array) #1 [internal function]: Zend\Navigation\Navigation->setAddClassToListItem(true) #2 C:\xampp\htdocs\fmi\vendor\zendframework\zendframework\library\Zend\View\Helper\Navigation\AbstractHelper.php(447): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\fmi\module\Application\view\layout\layout.phtml(35): Zend\View\Helper\Navigation\AbstractHelper->__call('setAddClassToLi...', Array) #4 C:\xampp\htdocs\fmi\module\Application\view\layout\layout.phtml(35): Zend\View\Helper\Navigation\Menu->setAddClassToListItem(true) #5 C:\xampp\htdocs\fmi\vendor\zendframework\zendframework\library\Zend\View\Renderer\PhpRenderer.php(507): include('C:\xa in C:\xampp\htdocs\fmi\vendor\zendframework\zendframework\library\Zend\Navigation\AbstractContainer.php on line 354.

Please can you give me the any suggestion for What can I do.

Looking forward to hear from you.

Thank you
Navin Patel

**Comment by coolcsn** [comment]
We have created the repo for different tutorials and educational purposes. So it may not work exactly right when you download and try to install. Try to isolate the problem by excluding the modules. Go to application.config.php and comment all modules except Application. Maybe you will get an error for routes used, but not defined. Check the view scripts and the layout in Application/view. Another words try to start your own skeleton application and take the modules from the repo and add them one by one toy your project,

**Comment by coolcsn** [comment]
Please, make sure you have the file " . / config / autoload / navigation.global.php ". Insite the file you should have the lines  https://github.com/wingman007/fmi/blob/master/config/autoload/navigation.global.php#L155-161 .  
...
'service_manager' => array(
         'factories' => array(
             'navigation' => 'Zend\Navigation\Service\DefaultNavigationFactory',
// 'secondary_navigation' => 'CsnNavigation\Navigation\Service\SecondaryNavigationFactory',
'secondary_navigation' => 'Csn\Zend\Navigation\Service\SecondaryNavigationFactory',
         ),
     ),
...
